### ISSUE TITLE
local_tournament.py sometimes hangs after a late action is provided

### ISSUE THREAD

**Issue by dmorrill10** [yotomyoto/KHex#4]
If an agent times out, but provides its action just after being given a `clear_board` command, `local_tournament.py` will hang. For example, my agent called `morrill` is playing against `Mopyhex`. `Mopyhex`, playing black, times out and ends the current game. `morrill` receives a `clear_board` command and returns just `=`. `Mopyhex` receives a `clear_board` command and sends `= e4`. `local_tournament.py` sends `valid` to `Mopyhex` even though it's `morrill`'s turn to act first. `local_tournament.py` then hangs.

Here is part of the raw terminal output from `local_tournament.py` that shows what I've described:

```
< genmove black
Game over, morrill (white) wins by timeout.

  A  B  C  D  E  F  
1  .  .  .  .  .  .  O
 2  .  .  .  .  .  .  O
  3  .  .  .  O  @  .  O
   4  .  .  .  .  .  .  O
    5  .  .  .  .  .  .  O
     6  .  .  .  .  .  .  O
         @  @  @  @  @  @  
e3 d3 x
         Mopyhex  morrill  
Mopyhex  xxxxxxx  1, 6     
morrill  7, 0     xxxxxxx  
< clear_board
> = 
> 
< clear_board
> = e4
> = 
> 
< valid
> = 
> 
```

**Comment by kenjyoung** [comment]
I didn't reproduce this exact issue, but timeouts were poorly handled to say the least. I tried to fix this up by adding locks on each program so they can't be accessed by multiple threads, something I should have obviously done in the first place. Also it should no longer send valid/occupied commands when a move has already timed out. Let me know if you still have similar issues.

I'm still not sure on the best way to handle timeouts, as it is now when a timed out agent has to start a new game it will politely wait for it to eventually pick a move and acknowledge the clear_board command. I might end up adding a (longer) timeout to the clear_board command as well so that a catatonic agent can't halt the whole tournament. Or perhaps it would be better to kill the timed-out program and restart it to give it a better chance to recover.
